// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutosizeTextarea: typeof import('./src/components/AutosizeTextarea.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChangePasswordModalBtn: typeof import('./src/components/Auth/ChangePasswordModalBtn.vue')['default']
    DeclareWinnerModal: typeof import('./src/components/Tournament/DeclareWinnerModal.vue')['default']
    EditBracketModal: typeof import('./src/components/Tournament/EditBracketModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    LoginModal: typeof import('./src/components/Auth/LoginModal.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Player: typeof import('./src/components/Player/Player.vue')['default']
    RegisterModal: typeof import('./src/components/Auth/RegisterModal.vue')['default']
    RemainingPlayers: typeof import('./src/components/Tournament/RemainingPlayers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    TournamentCard: typeof import('./src/components/Tournament/TournamentCard.vue')['default']
    TournamentFormModal: typeof import('./src/components/Tournament/TournamentFormModal.vue')['default']
    Tree: typeof import('./src/components/Tournament/Tree.vue')['default']
    TreeRound: typeof import('./src/components/Tournament/TreeRound.vue')['default']
    TreeRoundBracket: typeof import('./src/components/Tournament/TreeRoundBracket.vue')['default']
    TreeRoundBranch: typeof import('./src/components/Tournament/TreeRoundBranch.vue')['default']
  }
}

export {}
